alias ssh="ssh -X"

alias @LH-SVR1="ssh LH-SVR1"
alias @LH-SVR2="ssh LH-SVR2"
alias @LH-SVR3="ssh LH-SVR3"
alias @LH-SVR4="ssh LH-SVR4"
alias @LH-SVR5="ssh LH-SVR5"
alias @LH-SVR6="ssh LH-SVR6"
alias @LH-MAIN="ssh LH-MAIN"
alias @LH-LAB1="ssh LH-LAB1 -p 443"
alias @LH-NB1="ssh LH-NB1"
alias @LH-RP1="ssh LH-RP1"
